# Generated by Django 4.2.1 on 2023-05-19 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('car_photo_path', models.CharField(max_length=100, verbose_name='Фото автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='CarDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('driver_license', models.CharField(max_length=50, verbose_name='водительские права')),
                ('world_license', models.CharField(max_length=50, verbose_name='международные права')),
                ('registration', models.CharField(max_length=50, verbose_name='регистрация')),
                ('car_status', models.CharField(max_length=50, verbose_name='статус автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('rating', models.IntegerField(verbose_name='рейтинг')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car', verbose_name='автомобиль')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=100, verbose_name='откуда')),
                ('to_location', models.CharField(max_length=100, verbose_name='куда')),
                ('arrive_time', models.DateTimeField(verbose_name='время прибытия')),
                ('departure_time', models.DateTimeField(verbose_name='время отправления')),
                ('order_status', models.CharField(choices=[('P', 'Ожидание'), ('A', 'Принят'), ('C', 'Отменен'), ('F', 'Завершен')], default='P', max_length=1, verbose_name='статус заказа')),
                ('men_amount', models.IntegerField(verbose_name='количество мужчин')),
                ('children_amount', models.IntegerField(verbose_name='количество детей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('comment', models.TextField(verbose_name='комментарий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.driver', verbose_name='водитель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='оценка')),
                ('comment', models.TextField(verbose_name='комментарий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cardocument', verbose_name='документы автомобиля'),
        ),
    ]
