# Generated by Django 4.2.1 on 2023-05-19 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_car_options_alter_cardocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.car', verbose_name='автомобиль'),
        ),
    ]
