# Generated by Django 4.2.1 on 2023-05-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_car_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_status',
            field=models.CharField(choices=[('on_moderate', 'Ждет обработки'), ('moderating', 'В обработке'), ('approved', 'Одобрено')], default='on_moderate', max_length=50, verbose_name='статус автомобиля'),
        ),
    ]
