# Generated by Django 4.2.1 on 2023-05-19 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_driver_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.driver', verbose_name='водитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='men_amount',
            field=models.IntegerField(verbose_name='количество взрослых'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('P', 'Ожидание'), ('A', 'Принят'), ('C', 'Отменен'), ('F', 'Завершен')], default='P', max_length=1, null=True, verbose_name='статус заказа'),
        ),
    ]
