# Generated by Django 4.2.1 on 2023-05-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_car_car_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='car',
            name='driver_license',
        ),
        migrations.RemoveField(
            model_name='car',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='car',
            name='world_license',
        ),
        migrations.AddField(
            model_name='car',
            name='car_pass',
            field=models.CharField(default=1, max_length=255, verbose_name='Фото водительских прав'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='photo_with_car_pass',
            field=models.CharField(default=1, max_length=255, verbose_name='Фото автомобиля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='taxi_license',
            field=models.CharField(default=1, max_length=255, verbose_name='Лицензия на перевозку'),
            preserve_default=False,
        ),
    ]
