# Generated by Django 4.2.1 on 2023-05-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_car_date_created_remove_car_driver_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_pass',
            field=models.CharField(max_length=255, verbose_name='Регистрация ТС'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo_with_car_pass',
            field=models.CharField(max_length=255, verbose_name='Фото с правами'),
        ),
        migrations.AlterField(
            model_name='driverresponse',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность в часах'),
        ),
    ]
