# Generated by Django 4.2.1 on 2023-05-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_driverresponse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverresponse',
            name='status',
            field=models.CharField(choices=[('a', 'Выбран пользователем'), ('n', '')], default='n', max_length=1),
        ),
    ]
