# Generated by Django 4.2.1 on 2023-05-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_supportrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='request_status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('ongoing', 'В работе'), ('resolved', 'Решен')], max_length=20),
        ),
    ]
