# Generated by Django 4.2.1 on 2023-05-29 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_driverresponse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car',
            field=models.ForeignKey(blank=True, limit_choices_to={'car_status': 'approved'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.car', verbose_name='автомобиль'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.IntegerField(default=0, null=True, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='driverresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан в'),
        ),
        migrations.AlterField(
            model_name='driverresponse',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='driverresponse',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='driverresponse',
            name='status',
            field=models.CharField(choices=[('a', 'Выбран пользователем'), ('n', '')], default='n', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='description',
            field=models.TextField(verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('ongoing', 'В работе'), ('resolved', 'Решен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
