# Generated by Django 4.2.1 on 2023-05-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_car_car_pass_alter_car_photo_with_car_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_photo_path',
            field=models.ImageField(upload_to='car_photos', verbose_name='Фото автомобиля'),
        ),
    ]
