# Generated by Django 4.2.1 on 2023-05-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_supportrequest_request_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
    ]
