# Generated by Django 4.2.1 on 2023-05-21 11:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_order_rating_orderrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('publish', 'Published'), ('on_moder', 'On moderate')], default=1, max_length=8, verbose_name='Статус отзыва'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderrating',
            name='communication_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Коммуникация'),
        ),
        migrations.AlterField(
            model_name='orderrating',
            name='driver_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='orderrating',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderrating',
            name='transport_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Транспорт'),
        ),
        migrations.AlterUniqueTogether(
            name='orderrating',
            unique_together={('order',)},
        ),
    ]
