# Generated by Django 4.2.1 on 2023-05-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_feedback_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='order',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('publish', 'Опубликован'), ('on_moder', 'На обработке'), ('hiden', 'Скрыт')], max_length=8, verbose_name='Статус отзыва'),
        ),
    ]
