# Generated by Django 4.2.1 on 2023-05-21 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_feedback_order_alter_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('publish', 'Опубликован'), ('on_moder', 'На обработке'), ('hiden', 'Скрыт')], default='on_moder', max_length=8, verbose_name='Статус отзыва'),
        ),
    ]
