# Generated by Django 4.2.1 on 2023-05-21 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_feedback_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
    ]
