# Generated by Django 4.2.1 on 2023-05-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_feedback_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
