# Generated by Django 4.2.1 on 2023-05-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_feedback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='arrive_time',
        ),
    ]
